sonar.projectKey=intechcore_ngx_http_geoip2_module
sonar.organization=intechcore
sonar.projectName=ngx_http_geoip2_module

sonar.sources=.
sonar.exclusions=tests/**,keys/**,fuzz/**
sonar.tests=tests
sonar.test.exclusions=tests/fixtures/*.mmdb

# Written by the sonar job in .github/workflows/ci.yml.
sonar.cfamily.compile-commands=build/compile_commands.json
sonar.coverageReportPaths=build/coverage.xml
